#define ONLINE_MSG "[+] GATE ONLINE"
#define READ_MODE '\x00'

#define CMD_SERIAL_RD   0xFFFFFFF2
#define CMD_LCD_WRITE   0xFFFFFFF3
#define CMD_LCD_CLEAR   0xFFFFFFF4
#define CMD_SERVO_OPN   0xFFFFFFF5
#define CMD_SERVO_CLS   0xFFFFFFF6
#define CMD_SYS_RESET   0xFFFFFFF7 
